"""Deterministic service boundaries for API routes and future importer tools."""
from __future__ import annotations

from .data_loader import CatalogMode, load_catalog
from .explanations import reason_lost
from .fulfillment import allowed_methods, product_method_available
from .models import CanonicalProduct, Product, Vendor
from .normalizer import normalize_product, normalize_quantity
from .optimizer import optimize
from .schemas import (
    CatalogDiagnostics,
    CartPlan,
    ImportedProductCandidate,
    NormalizedProduct,
    OptimizeRequest,
    OptimizeResponse,
)


def _increment(counter: dict[str, int], key: str) -> None:
    counter[key] = counter.get(key, 0) + 1


def get_vendors(catalog_mode: CatalogMode = "imported_only") -> list[Vendor]:
    _, vendors = load_catalog(catalog_mode)
    return vendors


def get_products(catalog_mode: CatalogMode = "imported_only") -> list[NormalizedProduct]:
    products, _ = load_catalog(catalog_mode)
    return [normalize_product(product) for product in products]


def _optimizer_exclusion_reason(product: Product) -> str | None:
    if product.needs_review:
        return "needs_review"
    if product.missing_fields:
        return "missing_required_fields"
    if not product.in_stock:
        return "out_of_stock"
    normalized = normalize_product(product)
    if normalized.excluded:
        return normalized.exclusion_reason or "normalization_failed"
    if normalized.normalized_quantity is None:
        return "normalization_failed"
    return None


def optimizer_ready_products(
    products: list[Product],
    excluded_by_reason: dict[str, int] | None = None,
) -> list[Product]:
    """Normalize/filter catalog rows before optimizer matching.

    Imported product rows can be generated by multiple fetch runs. They already
    use the current Product schema (product_name/canonical_product/package_*),
    but duplicate equivalent variants make the brute-force package search blow
    up. Keep one optimizer-equivalent row, preferring the cheapest in-stock
    approved product.
    """
    ready: list[Product] = []
    best_by_key: dict[tuple, Product] = {}
    for product in products:
        reason = _optimizer_exclusion_reason(product)
        if reason is not None:
            if excluded_by_reason is not None:
                _increment(excluded_by_reason, reason)
            continue
        key = (
            product.vendor_id,
            product.canonical_product,
            product.package_quantity,
            product.package_unit,
            product.packaging,
            product.storage_state,
            product.is_unsalted,
            product.delivery_available,
            product.pickup_available,
            product.pickup_dropoff_available,
            product.ups_shipping_available,
            product.farm_truck_delivery_available,
            product.subscription_available,
            product.subscription_discount_percent,
            product.subscription_price,
            product.bulk_deal,
            product.container_deposit,
            product.container_returnable,
        )
        existing = best_by_key.get(key)
        if existing is None or product.price < existing.price:
            if existing is not None and excluded_by_reason is not None:
                _increment(excluded_by_reason, "deduped_equivalent")
            best_by_key[key] = product
        elif excluded_by_reason is not None:
            _increment(excluded_by_reason, "deduped_equivalent")
    ready.extend(best_by_key.values())
    return ready


def catalog_diagnostics(
    products: list[Product],
    ready_products: list[Product],
    excluded_by_reason: dict[str, int],
) -> CatalogDiagnostics:
    products_by_vendor: dict[str, int] = {}
    products_by_type: dict[str, int] = {}
    for product in products:
        _increment(products_by_vendor, product.vendor_id)
        _increment(products_by_type, product.canonical_product.value)
    return CatalogDiagnostics(
        approved_loaded_count=len(products),
        optimizer_ready_count=len(ready_products),
        products_by_vendor=dict(sorted(products_by_vendor.items())),
        products_by_type=dict(sorted(products_by_type.items())),
        excluded_by_reason=dict(sorted(excluded_by_reason.items())),
    )


def _candidate_products_for_item(
    item,
    products: list[Product],
    vendors: dict[str, Vendor],
    request: OptimizeRequest,
) -> list[Product]:
    canonical = item.canonical_product
    if canonical is None:
        return []
    packaging_preference = item.packaging_preference or request.packaging_preference
    storage_preference = item.storage_preference or request.storage_preference
    salt_preference = item.salt_preference or request.salt_preference
    excluded_vendors = set(request.excluded_vendor_ids)
    excluded_products = set(request.excluded_product_ids)
    methods = allowed_methods(request)
    candidates: list[Product] = []
    for product in products:
        if product.canonical_product != canonical:
            continue
        if product.vendor_id in excluded_vendors or product.id in excluded_products:
            continue
        vendor = vendors.get(product.vendor_id)
        if vendor is None:
            continue
        if not any(product_method_available(product, vendor, method) for method in methods):
            continue
        if request.fulfillment_mode in {"delivery_only", "ups_only"} and not product_method_available(product, vendor, "ups_shipping"):
            continue
        if request.fulfillment_mode == "pickup_only" and not product_method_available(product, vendor, "pickup_dropoff"):
            continue
        if packaging_preference == "glass_only" and product.packaging != "glass":
            continue
        if canonical == CanonicalProduct.butter and (
            (salt_preference == "salted" and product.is_unsalted) or (salt_preference == "unsalted" and not product.is_unsalted)
        ):
            continue
        if storage_preference == "fresh_only" and product.storage_state == "frozen":
            continue
        normalized = normalize_product(product)
        if normalized.excluded or normalized.normalized_quantity is None:
            continue
        candidates.append(product)
    return candidates


def _unavailable_reason_for_item(
    item,
    products: list[Product],
    ready_products: list[Product],
    vendors: dict[str, Vendor],
    request: OptimizeRequest,
) -> str:
    canonical = item.canonical_product
    if canonical is None:
        return "no_matching_product_type"
    matches = [product for product in products if product.canonical_product == canonical]
    if not matches:
        return "no_approved_products"
    if all(not product.in_stock for product in matches):
        return "all_matches_out_of_stock"
    try:
        normalize_quantity(canonical, item.quantity, item.unit)
    except Exception:
        return "invalid_requested_unit"
    unit_mappable = []
    for product in matches:
        try:
            normalized = normalize_product(product)
        except Exception:
            continue
        if normalized.normalized_quantity is not None:
            unit_mappable.append(product)
    if not unit_mappable:
        return "no_unit_mapping"
    if request.required_vendor_ids:
        required = set(request.required_vendor_ids) - set(request.excluded_vendor_ids)
        if required and not any(product.vendor_id in required for product in unit_mappable):
            return "vendor_forced_but_no_match"
    if request.excluded_vendor_ids and all(product.vendor_id in request.excluded_vendor_ids for product in unit_mappable):
        return "excluded_by_user"
    if request.excluded_product_ids and all(product.id in request.excluded_product_ids for product in unit_mappable):
        return "excluded_by_user"
    packaging_preference = item.packaging_preference or request.packaging_preference
    if packaging_preference == "glass_only":
        glass_matches = [product for product in matches if product.packaging == "glass"]
        if not glass_matches or all(not product.in_stock for product in glass_matches):
            return "requested_packaging_unavailable"
    candidates = _candidate_products_for_item(item, ready_products, vendors, request)
    if not candidates:
        return "no_valid_product_after_filters"
    return "no_valid_product_within_overbuy_limit"


def _replace_unavailable_reasons(
    response: OptimizeResponse,
    request: OptimizeRequest,
    products: list[Product],
    ready_products: list[Product],
    vendors: list[Vendor],
) -> OptimizeResponse:
    if not response.unavailable_items:
        return response
    vendor_map = {vendor.id: vendor for vendor in vendors}
    by_canonical = {
        item.canonical_product: item
        for item in request.items
        if item.canonical_product is not None
    }
    unavailable = []
    for item in response.unavailable_items:
        request_item = by_canonical.get(item.canonical_product)
        if request_item is None:
            unavailable.append(item)
            continue
        unavailable.append(
            item.model_copy(
                update={
                    "reason": _unavailable_reason_for_item(
                        request_item,
                        products,
                        ready_products,
                        vendor_map,
                        request,
                    )
                }
            )
        )
    return response.model_copy(update={"unavailable_items": unavailable})


def optimize_cart(request: OptimizeRequest) -> OptimizeResponse:
    products, vendors = load_catalog(request.catalog_mode)
    excluded_by_reason: dict[str, int] = {}
    ready = optimizer_ready_products(products, excluded_by_reason)
    diagnostics = catalog_diagnostics(products, ready, excluded_by_reason)
    response = _replace_unavailable_reasons(
        optimize(request, ready, vendors),
        request,
        products,
        ready,
        vendors,
    )
    return response.model_copy(update={"catalog_diagnostics": diagnostics})



def explain_cart(cart_plan: CartPlan, winner: CartPlan | None = None) -> list[str]:
    explanations = list(cart_plan.warnings) + list(cart_plan.notes)
    if winner is not None and cart_plan.rank != winner.rank:
        explanations.append(reason_lost(cart_plan, winner))
    return explanations


def validate_import_candidate(candidate: ImportedProductCandidate) -> ImportedProductCandidate:
    missing = set(candidate.missing_fields)
    warnings = list(dict.fromkeys(candidate.warnings))
    if candidate.eligibility_status == "excluded":
        return candidate.model_copy(
            update={
                "missing_fields": sorted(missing),
                "warnings": warnings,
                "needs_review": False,
            }
        )
    if candidate.product_type is None:
        missing.add("product_type")
    else:
        missing.discard("product_type")
    if candidate.detected_price is None:
        missing.add("detected_price")
    else:
        missing.discard("detected_price")
    if candidate.detected_package_size is None:
        missing.add("detected_package_size")
    else:
        missing.discard("detected_package_size")
    if candidate.detected_unit is None:
        missing.add("detected_unit")
    else:
        missing.discard("detected_unit")
    product_type = getattr(candidate.product_type, "value", candidate.product_type)
    unit = getattr(candidate.detected_unit, "value", candidate.detected_unit)
    if product_type in {"cow_milk", "sheep_milk", "cream"} and unit in {"lb", "oz"}:
        missing.add("invalid_package_for_product_type")
    if product_type in {"butter", "cheese"} and unit in {"gallon", "quart"}:
        # Pint-volume cheese is still accepted elsewhere for Example Farm A's
        # current cheese options; gallon/quart are too broad for optimizer use.
        missing.add("invalid_package_for_product_type")
    if product_type == "eggs" and unit in {"gallon", "quart", "pint", "lb", "oz"}:
        missing.add("invalid_package_for_product_type")
    scoped_name = (candidate.name or "").lower()
    if product_type == "cow_milk" and "cream" in scoped_name:
        missing.add("invalid_product_type_for_title")
    if product_type == "cow_milk" and "butter" in scoped_name and "buttermilk" not in scoped_name:
        missing.add("invalid_product_type_for_title")
    if (
        getattr(candidate.product_type, "value", candidate.product_type) == "cheese"
        and candidate.detected_unit is not None
        and getattr(candidate.detected_unit, "value", candidate.detected_unit) in {"pint", "quart", "gallon"}
    ):
        warnings = [
            warning
            for warning in warnings
            if warning != "needs optimizer unit mapping"
        ]
        if "needs optimizer unit mapping" not in warnings:
            warnings.append("needs optimizer unit mapping")
    # Only nag about parser confidence when required fields are actually missing.
    # A complete, eligible record (e.g. sheep milk with type/package/price/stock)
    # must not show a generic "below review threshold" warning.
    if (
        candidate.parser_confidence is not None
        and candidate.parser_confidence < 0.75
        and missing
    ):
        if "Parser confidence is below review threshold." not in warnings:
            warnings.append("Parser confidence is below review threshold.")
    else:
        warnings = [w for w in warnings if w != "Parser confidence is below review threshold."]
    return candidate.model_copy(
        update={
            "missing_fields": sorted(missing),
            "warnings": list(dict.fromkeys(warnings)),
            "needs_review": bool(missing) or candidate.eligibility_status == "needs_review",
        }
    )


def normalize_imported_product(candidate: ImportedProductCandidate) -> Product | None:
    checked = validate_import_candidate(candidate)
    if checked.eligibility_status == "excluded":
        return None
    if checked.missing_fields or checked.product_type is None:
        return None
    return Product(
        id=checked.import_id,
        vendor_id=checked.vendor_id,
        product_name=checked.name,
        canonical_product=checked.product_type,
        price=checked.detected_price or 0.0,
        package_quantity=checked.detected_package_size or 1.0,
        package_unit=checked.detected_unit,
        in_stock=checked.stock_status != "out_of_stock",
        packaging=checked.packaging,
        storage_state=checked.storage_state,
        source_type="imported",
        source_url=checked.source_url,
        parser_confidence=checked.parser_confidence,
        needs_review=checked.needs_review,
        raw_text=checked.raw_text,
        missing_fields=checked.missing_fields,
    )
